/** Flat admin permission registry — single source of truth. */
export const ALL_ADMIN_PERMISSIONS = [
  'admin.dashboard.view',
  'admin.notifications.read',
  'admin.notifications.manage',
  'admin.products.read',
  'admin.products.write',
  'admin.products.delete',
  'admin.products.publish',
  'admin.products.videos.read',
  'admin.inventory.read',
  'admin.inventory.adjust',
  'admin.orders.read',
  'admin.orders.write',
  'admin.orders.refund',
  'admin.orders.ship',
  'admin.trading.read',
  'admin.trading.settle',
  'admin.pricing.read',
  'admin.pricing.configure',
  'admin.pricing.override',
  'admin.users.read',
  'admin.users.write',
  'admin.kyc.read',
  'admin.kyc.review',
  'admin.finance.read',
  'admin.finance.reports',
  'admin.ledger.read',
  'admin.cms.read',
  'admin.cms.write',
  'admin.media.read',
  'admin.media.write',
  'admin.reports.view',
  'admin.reports.export',
  'admin.security.audit',
  'admin.security.sessions',
  'admin.security.rbac',
  'admin.settings.read',
  'admin.settings.write',
  'admin.tickets.read',
  'admin.tickets.write',
  'admin.tickets.manage',
] as const;

export type AdminPermissionKey = (typeof ALL_ADMIN_PERMISSIONS)[number];

export const ADMIN_PERMISSIONS = {
  dashboard: { view: 'admin.dashboard.view' },
  notifications: { read: 'admin.notifications.read', manage: 'admin.notifications.manage' },
  products: {
    read: 'admin.products.read',
    write: 'admin.products.write',
    delete: 'admin.products.delete',
    publish: 'admin.products.publish',
    videos: 'admin.products.videos.read',
  },
  inventory: { read: 'admin.inventory.read', adjust: 'admin.inventory.adjust' },
  orders: {
    read: 'admin.orders.read',
    write: 'admin.orders.write',
    refund: 'admin.orders.refund',
    ship: 'admin.orders.ship',
  },
  trading: { read: 'admin.trading.read', settle: 'admin.trading.settle' },
  pricing: {
    read: 'admin.pricing.read',
    configure: 'admin.pricing.configure',
    override: 'admin.pricing.override',
  },
  users: { read: 'admin.users.read', write: 'admin.users.write' },
  kyc: { read: 'admin.kyc.read', review: 'admin.kyc.review' },
  finance: { read: 'admin.finance.read', reports: 'admin.finance.reports' },
  ledger: { read: 'admin.ledger.read' },
  cms: { read: 'admin.cms.read', write: 'admin.cms.write' },
  media: { read: 'admin.media.read', write: 'admin.media.write' },
  reports: { view: 'admin.reports.view', export: 'admin.reports.export' },
  security: {
    audit: 'admin.security.audit',
    sessions: 'admin.security.sessions',
    rbac: 'admin.security.rbac',
  },
  settings: { read: 'admin.settings.read', write: 'admin.settings.write' },
  tickets: {
    read: 'admin.tickets.read',
    write: 'admin.tickets.write',
    manage: 'admin.tickets.manage',
  },
} as const satisfies Record<string, Record<string, AdminPermissionKey>>;
