import type { AdminPermissionKey } from './admin-permissions';
import { ADMIN_PERMISSIONS } from './admin-permissions';

export type AdminPageTemplate = 'dashboard' | 'list' | 'detail' | 'settings' | 'blank';

export type ApiAvailability = 'live' | 'partial' | 'pending';

export interface AdminRouteDefinition {
  id: string;
  path: string;
  label: string;
  sectionId: string;
  sectionLabel: string;
  template: AdminPageTemplate;
  permission: AdminPermissionKey;
  availability: ApiAvailability;
  description?: string;
  /** Parent route id for breadcrumbs (not path). */
  parentId?: string;
  /** If true, pathname may include dynamic segments after `path`. */
  dynamic?: boolean;
  /** Show in sidebar navigation. */
  nav?: boolean;
  /** Sort order within section (ascending). */
  navOrder?: number;
}

/** Single-vendor IA: retail jewelry → orders → melted gold → pricing → customers → finance → reports. */
export const ADMIN_ROUTE_SECTION_ORDER = [
  'overview',
  'catalog',
  'commerce',
  'trading',
  'pricing',
  'people',
  'finance',
  'reports',
  'content',
  'security',
  'settings',
] as const;

function r(
  def: Omit<AdminRouteDefinition, 'sectionId' | 'sectionLabel'> & {
    sectionId: string;
    sectionLabel: string;
  },
): AdminRouteDefinition {
  return def;
}

/** Single source of truth: navigation, breadcrumbs, guards, page metadata. */
export const ADMIN_ROUTES: AdminRouteDefinition[] = [
  // Overview
  r({
    id: 'dashboard',
    path: '/',
    label: 'داشبورد',
    sectionId: 'overview',
    sectionLabel: 'نمای کلی',
    template: 'dashboard',
    permission: ADMIN_PERMISSIONS.dashboard.view,
    availability: 'live',
    navOrder: 0,
  }),
  r({
    id: 'notifications.inbox',
    path: '/notifications',
    label: 'اعلان‌ها',
    sectionId: 'overview',
    sectionLabel: 'نمای کلی',
    template: 'list',
    permission: ADMIN_PERMISSIONS.notifications.read,
    availability: 'live',
    parentId: 'dashboard',
    navOrder: 10,
  }),
  r({
    id: 'notifications.templates',
    path: '/notifications/templates',
    label: 'قالب‌های اعلان',
    sectionId: 'overview',
    sectionLabel: 'نمای کلی',
    template: 'list',
    permission: ADMIN_PERMISSIONS.notifications.manage,
    availability: 'live',
    parentId: 'notifications.inbox',
    nav: false,
  }),
  r({
    id: 'notifications.rules',
    path: '/notifications/rules',
    label: 'قوانین اعلان',
    sectionId: 'overview',
    sectionLabel: 'نمای کلی',
    template: 'list',
    permission: ADMIN_PERMISSIONS.notifications.manage,
    availability: 'live',
    parentId: 'notifications.inbox',
    nav: false,
  }),
  r({
    id: 'notifications.delivery',
    path: '/notifications/delivery',
    label: 'لاگ ارسال پیام',
    sectionId: 'overview',
    sectionLabel: 'نمای کلی',
    template: 'list',
    permission: ADMIN_PERMISSIONS.notifications.read,
    availability: 'live',
    parentId: 'notifications.inbox',
    nav: false,
  }),

  // Catalog / PIM
  r({
    id: 'products.list',
    path: '/products',
    label: 'محصولات',
    sectionId: 'catalog',
    sectionLabel: 'فروشگاه (خرده)',
    template: 'list',
    permission: ADMIN_PERMISSIONS.products.read,
    availability: 'live',
    parentId: 'dashboard',
    navOrder: 10,
  }),
  r({
    id: 'products.new',
    path: '/products/new',
    label: 'محصول جدید',
    sectionId: 'catalog',
    sectionLabel: 'فروشگاه (خرده)',
    template: 'detail',
    permission: ADMIN_PERMISSIONS.products.write,
    availability: 'live',
    parentId: 'products.list',
    nav: false,
  }),
  r({
    id: 'products.detail',
    path: '/products',
    label: 'جزئیات محصول',
    sectionId: 'catalog',
    sectionLabel: 'فروشگاه (خرده)',
    template: 'detail',
    permission: ADMIN_PERMISSIONS.products.read,
    availability: 'live',
    parentId: 'products.list',
    dynamic: true,
    nav: false,
  }),
  r({
    id: 'products.edit',
    path: '/products',
    label: 'ویرایش محصول',
    sectionId: 'catalog',
    sectionLabel: 'فروشگاه (خرده)',
    template: 'detail',
    permission: ADMIN_PERMISSIONS.products.write,
    availability: 'live',
    parentId: 'products.detail',
    dynamic: true,
    nav: false,
  }),
  r({
    id: 'products.videos',
    path: '/products/videos',
    label: 'ویدیوهای محصول',
    sectionId: 'catalog',
    sectionLabel: 'فروشگاه (خرده)',
    template: 'list',
    permission: ADMIN_PERMISSIONS.products.videos,
    availability: 'live',
    parentId: 'products.list',
    nav: false,
  }),
  r({
    id: 'inventory.overview',
    path: '/inventory',
    label: 'موجودی انبار',
    sectionId: 'catalog',
    sectionLabel: 'فروشگاه (خرده)',
    template: 'list',
    permission: ADMIN_PERMISSIONS.inventory.read,
    availability: 'live',
    parentId: 'dashboard',
    navOrder: 20,
  }),
  r({
    id: 'inventory.history',
    path: '/inventory/history',
    label: 'تاریخچه موجودی',
    sectionId: 'catalog',
    sectionLabel: 'فروشگاه (خرده)',
    template: 'list',
    permission: ADMIN_PERMISSIONS.inventory.read,
    availability: 'live',
    parentId: 'inventory.overview',
    navOrder: 30,
  }),
  r({
    id: 'inventory.reports',
    path: '/inventory/reports',
    label: 'گزارش موجودی',
    sectionId: 'catalog',
    sectionLabel: 'فروشگاه (خرده)',
    template: 'list',
    permission: ADMIN_PERMISSIONS.inventory.read,
    availability: 'live',
    parentId: 'inventory.overview',
    nav: false,
    description: 'از بخش گزارش‌ها → گزارش موجودی',
  }),

  // Commerce
  r({
    id: 'orders.list',
    path: '/orders',
    label: 'سفارش‌ها',
    sectionId: 'commerce',
    sectionLabel: 'سفارش خرده',
    template: 'list',
    permission: ADMIN_PERMISSIONS.orders.read,
    availability: 'live',
    parentId: 'dashboard',
    navOrder: 10,
  }),
  r({
    id: 'orders.detail',
    path: '/orders',
    label: 'جزئیات سفارش',
    sectionId: 'commerce',
    sectionLabel: 'فروش',
    template: 'detail',
    permission: ADMIN_PERMISSIONS.orders.read,
    availability: 'live',
    parentId: 'orders.list',
    dynamic: true,
    nav: false,
  }),

  // Trading
  r({
    id: 'trading.buy',
    path: '/trading/buy-orders',
    label: 'سفارش خرید',
    sectionId: 'trading',
    sectionLabel: 'طلای آب‌شده',
    template: 'list',
    permission: ADMIN_PERMISSIONS.trading.read,
    availability: 'live',
    parentId: 'trading.history',
    nav: false,
    description: 'فیلتر خرید در صفحه معاملات',
  }),
  r({
    id: 'trading.sell',
    path: '/trading/sell-orders',
    label: 'سفارش فروش',
    sectionId: 'trading',
    sectionLabel: 'طلای آب‌شده',
    template: 'list',
    permission: ADMIN_PERMISSIONS.trading.read,
    availability: 'live',
    parentId: 'trading.history',
    nav: false,
    description: 'فیلتر فروش در صفحه معاملات',
  }),
  r({
    id: 'trading.history',
    path: '/trading/history',
    label: 'معاملات',
    sectionId: 'trading',
    sectionLabel: 'طلای آب‌شده',
    template: 'list',
    permission: ADMIN_PERMISSIONS.trading.read,
    availability: 'live',
    parentId: 'dashboard',
    navOrder: 10,
  }),
  r({
    id: 'trading.settlement',
    path: '/trading/settlement',
    label: 'تسویه',
    sectionId: 'trading',
    sectionLabel: 'طلای آب‌شده',
    template: 'list',
    permission: ADMIN_PERMISSIONS.trading.settle,
    availability: 'live',
    parentId: 'dashboard',
    navOrder: 20,
  }),
  r({
    id: 'trading.reports',
    path: '/trading/reports',
    label: 'گزارش معاملات',
    sectionId: 'trading',
    sectionLabel: 'طلای آب‌شده',
    template: 'list',
    permission: ADMIN_PERMISSIONS.reports.view,
    availability: 'live',
    parentId: 'dashboard',
    nav: false,
    description: 'از بخش گزارش‌ها → گزارش معاملات',
  }),

  // Pricing
  r({
    id: 'pricing.live',
    path: '/pricing/live',
    label: 'قیمت زنده',
    sectionId: 'pricing',
    sectionLabel: 'قیمت‌گذاری',
    template: 'list',
    permission: ADMIN_PERMISSIONS.pricing.read,
    availability: 'live',
    parentId: 'dashboard',
    navOrder: 10,
  }),
  r({
    id: 'pricing.history',
    path: '/pricing/history',
    label: 'تاریخچه قیمت',
    sectionId: 'pricing',
    sectionLabel: 'قیمت‌گذاری',
    template: 'list',
    permission: ADMIN_PERMISSIONS.pricing.read,
    availability: 'live',
    parentId: 'dashboard',
    navOrder: 20,
  }),
  r({
    id: 'pricing.providers',
    path: '/pricing/providers',
    label: 'ارائه‌دهندگان',
    sectionId: 'pricing',
    sectionLabel: 'قیمت‌گذاری',
    template: 'settings',
    permission: ADMIN_PERMISSIONS.pricing.configure,
    availability: 'live',
    parentId: 'dashboard',
    navOrder: 30,
  }),
  r({
    id: 'pricing.margins',
    path: '/pricing/margins',
    label: 'حاشیه سود و کارمزد',
    sectionId: 'pricing',
    sectionLabel: 'قیمت‌گذاری',
    template: 'settings',
    permission: ADMIN_PERMISSIONS.pricing.configure,
    availability: 'live',
    parentId: 'dashboard',
    navOrder: 40,
  }),
  r({
    id: 'pricing.overrides',
    path: '/pricing/overrides',
    label: 'بازنویسی قیمت',
    sectionId: 'pricing',
    sectionLabel: 'قیمت‌گذاری',
    template: 'settings',
    permission: ADMIN_PERMISSIONS.pricing.override,
    availability: 'live',
    parentId: 'dashboard',
    navOrder: 50,
  }),

  // People
  r({
    id: 'users.list',
    path: '/users',
    label: 'کاربران',
    sectionId: 'people',
    sectionLabel: 'مشتریان',
    template: 'list',
    permission: ADMIN_PERMISSIONS.users.read,
    availability: 'live',
    parentId: 'dashboard',
    navOrder: 10,
  }),
  r({
    id: 'users.detail',
    path: '/users',
    label: 'جزئیات کاربر',
    sectionId: 'people',
    sectionLabel: 'کاربران',
    template: 'detail',
    permission: ADMIN_PERMISSIONS.users.read,
    availability: 'live',
    parentId: 'users.list',
    dynamic: true,
    nav: false,
  }),
  r({
    id: 'users.kyc',
    path: '/users/kyc',
    label: 'احراز هویت (KYC)',
    sectionId: 'people',
    sectionLabel: 'مشتریان',
    template: 'list',
    permission: ADMIN_PERMISSIONS.kyc.read,
    availability: 'live',
    parentId: 'dashboard',
    navOrder: 20,
  }),
  r({
    id: 'users.roles',
    path: '/users/roles',
    label: 'نقش‌ها',
    sectionId: 'people',
    sectionLabel: 'مشتریان',
    template: 'settings',
    permission: ADMIN_PERMISSIONS.security.rbac,
    availability: 'partial',
    parentId: 'users.list',
    nav: false,
    description: 'از بخش امنیت → مدیریت نقش',
  }),
  r({
    id: 'users.permissions',
    path: '/users/permissions',
    label: 'دسترسی‌ها',
    sectionId: 'people',
    sectionLabel: 'مشتریان',
    template: 'settings',
    permission: ADMIN_PERMISSIONS.security.rbac,
    availability: 'pending',
    parentId: 'users.list',
    nav: false,
    description: 'از بخش امنیت → مدیریت دسترسی',
  }),

  // Finance
  r({
    id: 'finance.wallets',
    path: '/finance/wallets',
    label: 'کیف پول‌ها',
    sectionId: 'finance',
    sectionLabel: 'مالی',
    template: 'list',
    permission: ADMIN_PERMISSIONS.finance.read,
    availability: 'live',
    parentId: 'dashboard',
    navOrder: 10,
  }),
  r({
    id: 'finance.transactions',
    path: '/finance/transactions',
    label: 'تراکنش‌ها',
    sectionId: 'finance',
    sectionLabel: 'مالی',
    template: 'list',
    permission: ADMIN_PERMISSIONS.finance.read,
    availability: 'live',
    parentId: 'dashboard',
    navOrder: 20,
  }),
  r({
    id: 'finance.ledger',
    path: '/finance/ledger',
    label: 'دفتر کل',
    sectionId: 'finance',
    sectionLabel: 'مالی',
    template: 'list',
    permission: ADMIN_PERMISSIONS.ledger.read,
    availability: 'live',
    parentId: 'dashboard',
    navOrder: 30,
  }),
  r({
    id: 'finance.accounting',
    path: '/finance/accounting',
    label: 'حسابداری',
    sectionId: 'finance',
    sectionLabel: 'مالی',
    template: 'list',
    permission: ADMIN_PERMISSIONS.ledger.read,
    availability: 'live',
    parentId: 'dashboard',
    navOrder: 40,
  }),
  r({
    id: 'finance.reports',
    path: '/finance/reports',
    label: 'گزارش مالی',
    sectionId: 'finance',
    sectionLabel: 'مالی',
    template: 'list',
    permission: ADMIN_PERMISSIONS.finance.reports,
    availability: 'live',
    parentId: 'dashboard',
    nav: false,
    description: 'از بخش گزارش‌ها → گزارش مالی',
  }),

  // Content
  r({
    id: 'cms.blog',
    path: '/cms/blog',
    label: 'وبلاگ',
    sectionId: 'content',
    sectionLabel: 'محتوا و رسانه',
    template: 'list',
    permission: ADMIN_PERMISSIONS.cms.read,
    availability: 'live',
    parentId: 'dashboard',
  }),
  r({
    id: 'cms.homepage',
    path: '/cms/homepage',
    label: 'صفحه اصلی',
    sectionId: 'content',
    sectionLabel: 'محتوا و رسانه',
    template: 'settings',
    permission: ADMIN_PERMISSIONS.cms.write,
    availability: 'live',
    parentId: 'dashboard',
  }),
  r({
    id: 'cms.banners',
    path: '/cms/banners',
    label: 'بنرها',
    sectionId: 'content',
    sectionLabel: 'محتوا و رسانه',
    template: 'list',
    permission: ADMIN_PERMISSIONS.cms.write,
    availability: 'live',
    parentId: 'dashboard',
  }),
  r({
    id: 'cms.faq',
    path: '/cms/faq',
    label: 'سوالات متداول',
    sectionId: 'content',
    sectionLabel: 'محتوا و رسانه',
    template: 'list',
    permission: ADMIN_PERMISSIONS.cms.write,
    availability: 'live',
    parentId: 'dashboard',
  }),
  r({
    id: 'cms.seo',
    path: '/cms/seo',
    label: 'SEO',
    sectionId: 'content',
    sectionLabel: 'محتوا و رسانه',
    template: 'settings',
    permission: ADMIN_PERMISSIONS.cms.write,
    availability: 'live',
    parentId: 'dashboard',
  }),
  r({
    id: 'cms.pages',
    path: '/cms/pages',
    label: 'صفحات ثابت',
    sectionId: 'content',
    sectionLabel: 'محتوا و رسانه',
    template: 'list',
    permission: ADMIN_PERMISSIONS.cms.read,
    availability: 'live',
    parentId: 'dashboard',
  }),
  r({
    id: 'media.library',
    path: '/media',
    label: 'کتابخانه رسانه',
    sectionId: 'content',
    sectionLabel: 'محتوا و رسانه',
    template: 'list',
    permission: ADMIN_PERMISSIONS.media.read,
    availability: 'live',
    parentId: 'dashboard',
  }),
  r({
    id: 'media.upload',
    path: '/media/upload',
    label: 'آپلود',
    sectionId: 'content',
    sectionLabel: 'محتوا و رسانه',
    template: 'blank',
    permission: ADMIN_PERMISSIONS.media.write,
    availability: 'live',
    parentId: 'media.library',
    nav: false,
  }),

  // Reports
  r({
    id: 'reports.sales',
    path: '/reports/sales',
    label: 'گزارش فروش',
    sectionId: 'reports',
    sectionLabel: 'گزارش‌ها',
    template: 'list',
    permission: ADMIN_PERMISSIONS.reports.view,
    availability: 'live',
    parentId: 'dashboard',
    navOrder: 10,
  }),
  r({
    id: 'reports.inventory',
    path: '/reports/inventory',
    label: 'گزارش موجودی',
    sectionId: 'reports',
    sectionLabel: 'گزارش‌ها',
    template: 'list',
    permission: ADMIN_PERMISSIONS.reports.view,
    availability: 'live',
    parentId: 'dashboard',
    navOrder: 20,
  }),
  r({
    id: 'reports.users',
    path: '/reports/users',
    label: 'گزارش کاربران',
    sectionId: 'reports',
    sectionLabel: 'گزارش‌ها',
    template: 'list',
    permission: ADMIN_PERMISSIONS.reports.view,
    availability: 'live',
    parentId: 'dashboard',
    navOrder: 30,
  }),
  r({
    id: 'reports.trading',
    path: '/reports/trading',
    label: 'گزارش معاملات',
    sectionId: 'reports',
    sectionLabel: 'گزارش‌ها',
    template: 'list',
    permission: ADMIN_PERMISSIONS.reports.view,
    availability: 'live',
    parentId: 'dashboard',
    navOrder: 40,
  }),
  r({
    id: 'reports.financial',
    path: '/reports/financial',
    label: 'گزارش مالی',
    sectionId: 'reports',
    sectionLabel: 'گزارش‌ها',
    template: 'list',
    permission: ADMIN_PERMISSIONS.reports.view,
    availability: 'live',
    parentId: 'dashboard',
    navOrder: 50,
  }),

  // Security
  r({
    id: 'security.audit',
    path: '/security/audit',
    label: 'لاگ ممیزی',
    sectionId: 'security',
    sectionLabel: 'امنیت',
    template: 'list',
    permission: ADMIN_PERMISSIONS.security.audit,
    availability: 'live',
    parentId: 'dashboard',
  }),
  r({
    id: 'security.sessions',
    path: '/security/sessions',
    label: 'نشست‌ها',
    sectionId: 'security',
    sectionLabel: 'امنیت',
    template: 'list',
    permission: ADMIN_PERMISSIONS.security.sessions,
    availability: 'live',
    parentId: 'dashboard',
  }),
  r({
    id: 'security.loginHistory',
    path: '/security/login-history',
    label: 'تاریخچه ورود',
    sectionId: 'security',
    sectionLabel: 'امنیت',
    template: 'list',
    permission: ADMIN_PERMISSIONS.security.audit,
    availability: 'live',
    parentId: 'dashboard',
  }),
  r({
    id: 'security.roles',
    path: '/security/roles',
    label: 'مدیریت نقش',
    sectionId: 'security',
    sectionLabel: 'امنیت',
    template: 'settings',
    permission: ADMIN_PERMISSIONS.security.rbac,
    availability: 'live',
    parentId: 'dashboard',
  }),
  r({
    id: 'security.permissions',
    path: '/security/permissions',
    label: 'مدیریت دسترسی',
    sectionId: 'security',
    sectionLabel: 'امنیت',
    template: 'settings',
    permission: ADMIN_PERMISSIONS.security.rbac,
    availability: 'live',
    parentId: 'dashboard',
  }),

  // Settings
  r({
    id: 'settings.home',
    path: '/settings',
    label: 'تنظیمات',
    sectionId: 'settings',
    sectionLabel: 'تنظیمات سیستم',
    template: 'settings',
    permission: ADMIN_PERMISSIONS.settings.read,
    availability: 'partial',
    parentId: 'dashboard',
  }),
  r({
    id: 'settings.general',
    path: '/settings/general',
    label: 'عمومی',
    sectionId: 'settings',
    sectionLabel: 'تنظیمات سیستم',
    template: 'settings',
    permission: ADMIN_PERMISSIONS.settings.read,
    availability: 'partial',
    parentId: 'settings.home',
  }),
  r({
    id: 'settings.commerce',
    path: '/settings/commerce',
    label: 'تجارت',
    sectionId: 'settings',
    sectionLabel: 'تنظیمات سیستم',
    template: 'settings',
    permission: ADMIN_PERMISSIONS.settings.write,
    availability: 'partial',
    parentId: 'settings.home',
  }),
  r({
    id: 'settings.gold',
    path: '/settings/gold',
    label: 'طلا',
    sectionId: 'settings',
    sectionLabel: 'تنظیمات سیستم',
    template: 'settings',
    permission: ADMIN_PERMISSIONS.settings.write,
    availability: 'pending',
    parentId: 'settings.home',
  }),
  r({
    id: 'settings.featureFlags',
    path: '/settings/feature-flags',
    label: 'قابلیت‌ها',
    sectionId: 'settings',
    sectionLabel: 'تنظیمات سیستم',
    template: 'settings',
    permission: ADMIN_PERMISSIONS.settings.write,
    availability: 'partial',
    parentId: 'settings.home',
  }),
];

export const ADMIN_ROUTE_BY_ID = Object.fromEntries(
  ADMIN_ROUTES.map((route) => [route.id, route]),
) as Record<string, AdminRouteDefinition>;

/** Routes visible in sidebar (`nav !== false`). */
export const ADMIN_NAV_ROUTES = ADMIN_ROUTES.filter((route) => route.nav !== false);
