import type { AdminPermissionKey } from './admin-permissions';
import { ADMIN_PERMISSIONS } from './admin-permissions';

export type AdminPageTemplate = 'dashboard' | 'list' | 'detail' | 'settings' | 'blank';

export type ApiAvailability = 'live' | 'partial' | 'pending';

export interface AdminRouteDefinition {
  id: string;
  path: string;
  label: string;
  sectionId: string;
  sectionLabel: string;
  template: AdminPageTemplate;
  permission: AdminPermissionKey;
  availability: ApiAvailability;
  description?: string;
  /** Parent route id for breadcrumbs (not path). */
  parentId?: string;
  /** If true, pathname may include dynamic segments after `path`. */
  dynamic?: boolean;
  /** Show in sidebar navigation. */
  nav?: boolean;
}

export const ADMIN_ROUTE_SECTION_ORDER = [
  'overview',
  'catalog',
  'commerce',
  'trading',
  'pricing',
  'people',
  'finance',
  'content',
  'realtime',
  'reports',
  'security',
  'settings',
] as const;

function r(
  def: Omit<AdminRouteDefinition, 'sectionId' | 'sectionLabel'> & {
    sectionId: string;
    sectionLabel: string;
  },
): AdminRouteDefinition {
  return def;
}

/** Single source of truth: navigation, breadcrumbs, guards, page metadata. */
export const ADMIN_ROUTES: AdminRouteDefinition[] = [
  // Overview
  r({
    id: 'dashboard',
    path: '/',
    label: 'داشبورد',
    sectionId: 'overview',
    sectionLabel: 'نمای کلی',
    template: 'dashboard',
    permission: ADMIN_PERMISSIONS.dashboard.view,
    availability: 'live',
  }),
  r({
    id: 'notifications.inbox',
    path: '/notifications',
    label: 'مرکز اعلان‌ها',
    sectionId: 'overview',
    sectionLabel: 'نمای کلی',
    template: 'list',
    permission: ADMIN_PERMISSIONS.notifications.read,
    availability: 'pending',
    parentId: 'dashboard',
  }),
  r({
    id: 'notifications.templates',
    path: '/notifications/templates',
    label: 'قالب‌ها',
    sectionId: 'overview',
    sectionLabel: 'نمای کلی',
    template: 'list',
    permission: ADMIN_PERMISSIONS.notifications.manage,
    availability: 'pending',
    parentId: 'notifications.inbox',
  }),
  r({
    id: 'notifications.rules',
    path: '/notifications/rules',
    label: 'قوانین',
    sectionId: 'overview',
    sectionLabel: 'نمای کلی',
    template: 'list',
    permission: ADMIN_PERMISSIONS.notifications.manage,
    availability: 'pending',
    parentId: 'notifications.inbox',
  }),
  r({
    id: 'notifications.delivery',
    path: '/notifications/delivery',
    label: 'تحویل',
    sectionId: 'overview',
    sectionLabel: 'نمای کلی',
    template: 'list',
    permission: ADMIN_PERMISSIONS.notifications.read,
    availability: 'pending',
    parentId: 'notifications.inbox',
  }),

  // Catalog / PIM
  r({
    id: 'products.list',
    path: '/products',
    label: 'محصولات',
    sectionId: 'catalog',
    sectionLabel: 'محصول و کاتالوگ',
    template: 'list',
    permission: ADMIN_PERMISSIONS.products.read,
    availability: 'partial',
    parentId: 'dashboard',
  }),
  r({
    id: 'products.new',
    path: '/products/new',
    label: 'محصول جدید',
    sectionId: 'catalog',
    sectionLabel: 'محصول و کاتالوگ',
    template: 'detail',
    permission: ADMIN_PERMISSIONS.products.write,
    availability: 'pending',
    parentId: 'products.list',
  }),
  r({
    id: 'products.detail',
    path: '/products',
    label: 'جزئیات محصول',
    sectionId: 'catalog',
    sectionLabel: 'محصول و کاتالوگ',
    template: 'detail',
    permission: ADMIN_PERMISSIONS.products.read,
    availability: 'partial',
    parentId: 'products.list',
    dynamic: true,
    nav: false,
  }),
  r({
    id: 'products.edit',
    path: '/products',
    label: 'ویرایش محصول',
    sectionId: 'catalog',
    sectionLabel: 'محصول و کاتالوگ',
    template: 'detail',
    permission: ADMIN_PERMISSIONS.products.write,
    availability: 'pending',
    parentId: 'products.detail',
    dynamic: true,
    nav: false,
  }),
  r({
    id: 'products.certificates',
    path: '/products/certificates',
    label: 'گواهی‌ها',
    sectionId: 'catalog',
    sectionLabel: 'محصول و کاتالوگ',
    template: 'list',
    permission: ADMIN_PERMISSIONS.products.certificates,
    availability: 'pending',
    parentId: 'products.list',
  }),
  r({
    id: 'products.videos',
    path: '/products/videos',
    label: 'ویدیوها',
    sectionId: 'catalog',
    sectionLabel: 'محصول و کاتالوگ',
    template: 'list',
    permission: ADMIN_PERMISSIONS.products.videos,
    availability: 'pending',
    parentId: 'products.list',
  }),
  r({
    id: 'inventory.overview',
    path: '/inventory',
    label: 'موجودی انبار',
    sectionId: 'catalog',
    sectionLabel: 'محصول و کاتالوگ',
    template: 'list',
    permission: ADMIN_PERMISSIONS.inventory.read,
    availability: 'pending',
    parentId: 'dashboard',
  }),
  r({
    id: 'inventory.adjustments',
    path: '/inventory/adjustments',
    label: 'تعدیل موجودی',
    sectionId: 'catalog',
    sectionLabel: 'محصول و کاتالوگ',
    template: 'list',
    permission: ADMIN_PERMISSIONS.inventory.adjust,
    availability: 'pending',
    parentId: 'inventory.overview',
  }),
  r({
    id: 'inventory.history',
    path: '/inventory/history',
    label: 'تاریخچه',
    sectionId: 'catalog',
    sectionLabel: 'محصول و کاتالوگ',
    template: 'list',
    permission: ADMIN_PERMISSIONS.inventory.read,
    availability: 'pending',
    parentId: 'inventory.overview',
  }),
  r({
    id: 'inventory.reports',
    path: '/inventory/reports',
    label: 'گزارش موجودی',
    sectionId: 'catalog',
    sectionLabel: 'محصول و کاتالوگ',
    template: 'list',
    permission: ADMIN_PERMISSIONS.inventory.read,
    availability: 'pending',
    parentId: 'inventory.overview',
  }),

  // Commerce
  r({
    id: 'orders.list',
    path: '/orders',
    label: 'سفارش‌ها',
    sectionId: 'commerce',
    sectionLabel: 'فروش',
    template: 'list',
    permission: ADMIN_PERMISSIONS.orders.read,
    availability: 'pending',
    parentId: 'dashboard',
  }),
  r({
    id: 'orders.detail',
    path: '/orders',
    label: 'جزئیات سفارش',
    sectionId: 'commerce',
    sectionLabel: 'فروش',
    template: 'detail',
    permission: ADMIN_PERMISSIONS.orders.read,
    availability: 'pending',
    parentId: 'orders.list',
    dynamic: true,
    nav: false,
  }),

  // Trading
  r({
    id: 'trading.buy',
    path: '/trading/buy-orders',
    label: 'سفارش خرید',
    sectionId: 'trading',
    sectionLabel: 'معاملات طلا',
    template: 'list',
    permission: ADMIN_PERMISSIONS.trading.read,
    availability: 'live',
    parentId: 'dashboard',
  }),
  r({
    id: 'trading.sell',
    path: '/trading/sell-orders',
    label: 'سفارش فروش',
    sectionId: 'trading',
    sectionLabel: 'معاملات طلا',
    template: 'list',
    permission: ADMIN_PERMISSIONS.trading.read,
    availability: 'live',
    parentId: 'dashboard',
  }),
  r({
    id: 'trading.history',
    path: '/trading/history',
    label: 'تاریخچه معاملات',
    sectionId: 'trading',
    sectionLabel: 'معاملات طلا',
    template: 'list',
    permission: ADMIN_PERMISSIONS.trading.read,
    availability: 'live',
    parentId: 'dashboard',
  }),
  r({
    id: 'trading.settlement',
    path: '/trading/settlement',
    label: 'تسویه',
    sectionId: 'trading',
    sectionLabel: 'معاملات طلا',
    template: 'list',
    permission: ADMIN_PERMISSIONS.trading.settle,
    availability: 'pending',
    parentId: 'dashboard',
  }),
  r({
    id: 'trading.reports',
    path: '/trading/reports',
    label: 'گزارش معاملات',
    sectionId: 'trading',
    sectionLabel: 'معاملات طلا',
    template: 'list',
    permission: ADMIN_PERMISSIONS.reports.view,
    availability: 'pending',
    parentId: 'dashboard',
  }),

  // Pricing
  r({
    id: 'pricing.live',
    path: '/pricing/live',
    label: 'قیمت زنده',
    sectionId: 'pricing',
    sectionLabel: 'قیمت‌گذاری',
    template: 'list',
    permission: ADMIN_PERMISSIONS.pricing.read,
    availability: 'live',
    parentId: 'dashboard',
  }),
  r({
    id: 'pricing.history',
    path: '/pricing/history',
    label: 'تاریخچه قیمت',
    sectionId: 'pricing',
    sectionLabel: 'قیمت‌گذاری',
    template: 'list',
    permission: ADMIN_PERMISSIONS.pricing.read,
    availability: 'live',
    parentId: 'dashboard',
  }),
  r({
    id: 'pricing.providers',
    path: '/pricing/providers',
    label: 'ارائه‌دهندگان',
    sectionId: 'pricing',
    sectionLabel: 'قیمت‌گذاری',
    template: 'settings',
    permission: ADMIN_PERMISSIONS.pricing.configure,
    availability: 'pending',
    parentId: 'dashboard',
  }),
  r({
    id: 'pricing.margins',
    path: '/pricing/margins',
    label: 'حاشیه سود',
    sectionId: 'pricing',
    sectionLabel: 'قیمت‌گذاری',
    template: 'settings',
    permission: ADMIN_PERMISSIONS.pricing.configure,
    availability: 'pending',
    parentId: 'dashboard',
  }),
  r({
    id: 'pricing.commissions',
    path: '/pricing/commissions',
    label: 'کارمزد',
    sectionId: 'pricing',
    sectionLabel: 'قیمت‌گذاری',
    template: 'settings',
    permission: ADMIN_PERMISSIONS.pricing.configure,
    availability: 'pending',
    parentId: 'dashboard',
  }),
  r({
    id: 'pricing.overrides',
    path: '/pricing/overrides',
    label: 'بازنویسی قیمت',
    sectionId: 'pricing',
    sectionLabel: 'قیمت‌گذاری',
    template: 'settings',
    permission: ADMIN_PERMISSIONS.pricing.override,
    availability: 'pending',
    parentId: 'dashboard',
  }),

  // People
  r({
    id: 'users.list',
    path: '/users',
    label: 'کاربران',
    sectionId: 'people',
    sectionLabel: 'کاربران و فروشندگان',
    template: 'list',
    permission: ADMIN_PERMISSIONS.users.read,
    availability: 'live',
    parentId: 'dashboard',
  }),
  r({
    id: 'users.detail',
    path: '/users',
    label: 'جزئیات کاربر',
    sectionId: 'people',
    sectionLabel: 'کاربران و فروشندگان',
    template: 'detail',
    permission: ADMIN_PERMISSIONS.users.read,
    availability: 'pending',
    parentId: 'users.list',
    dynamic: true,
    nav: false,
  }),
  r({
    id: 'users.kyc',
    path: '/users/kyc',
    label: 'احراز هویت',
    sectionId: 'people',
    sectionLabel: 'کاربران و فروشندگان',
    template: 'list',
    permission: ADMIN_PERMISSIONS.kyc.read,
    availability: 'live',
    parentId: 'dashboard',
  }),
  r({
    id: 'users.roles',
    path: '/users/roles',
    label: 'نقش‌ها',
    sectionId: 'people',
    sectionLabel: 'کاربران و فروشندگان',
    template: 'settings',
    permission: ADMIN_PERMISSIONS.security.rbac,
    availability: 'partial',
    parentId: 'users.list',
  }),
  r({
    id: 'users.permissions',
    path: '/users/permissions',
    label: 'دسترسی‌ها',
    sectionId: 'people',
    sectionLabel: 'کاربران و فروشندگان',
    template: 'settings',
    permission: ADMIN_PERMISSIONS.security.rbac,
    availability: 'pending',
    parentId: 'users.list',
  }),
  r({
    id: 'vendors.list',
    path: '/vendors',
    label: 'فروشندگان',
    sectionId: 'people',
    sectionLabel: 'کاربران و فروشندگان',
    template: 'list',
    permission: ADMIN_PERMISSIONS.vendors.read,
    availability: 'pending',
    parentId: 'dashboard',
  }),
  r({
    id: 'vendors.applications',
    path: '/vendors/applications',
    label: 'درخواست فروشندگی',
    sectionId: 'people',
    sectionLabel: 'کاربران و فروشندگان',
    template: 'list',
    permission: ADMIN_PERMISSIONS.vendors.approve,
    availability: 'pending',
    parentId: 'vendors.list',
  }),
  r({
    id: 'vendors.verification',
    path: '/vendors/verification',
    label: 'تأیید فروشنده',
    sectionId: 'people',
    sectionLabel: 'کاربران و فروشندگان',
    template: 'list',
    permission: ADMIN_PERMISSIONS.vendors.approve,
    availability: 'pending',
    parentId: 'vendors.list',
  }),
  r({
    id: 'vendors.products',
    path: '/vendors/products',
    label: 'محصولات فروشنده',
    sectionId: 'people',
    sectionLabel: 'کاربران و فروشندگان',
    template: 'list',
    permission: ADMIN_PERMISSIONS.vendors.read,
    availability: 'pending',
    parentId: 'vendors.list',
  }),
  r({
    id: 'vendors.settlement',
    path: '/vendors/settlement',
    label: 'تسویه فروشنده',
    sectionId: 'people',
    sectionLabel: 'کاربران و فروشندگان',
    template: 'list',
    permission: ADMIN_PERMISSIONS.vendors.settlement,
    availability: 'pending',
    parentId: 'vendors.list',
  }),
  r({
    id: 'vendors.commission',
    path: '/vendors/commission',
    label: 'کمیسیون',
    sectionId: 'people',
    sectionLabel: 'کاربران و فروشندگان',
    template: 'settings',
    permission: ADMIN_PERMISSIONS.vendors.commission,
    availability: 'pending',
    parentId: 'vendors.list',
  }),
  r({
    id: 'vendors.payouts',
    path: '/vendors/payouts',
    label: 'پرداخت‌ها',
    sectionId: 'people',
    sectionLabel: 'کاربران و فروشندگان',
    template: 'list',
    permission: ADMIN_PERMISSIONS.vendors.payout,
    availability: 'pending',
    parentId: 'vendors.list',
  }),
  r({
    id: 'vendors.reports',
    path: '/vendors/reports',
    label: 'گزارش فروشنده',
    sectionId: 'people',
    sectionLabel: 'کاربران و فروشندگان',
    template: 'list',
    permission: ADMIN_PERMISSIONS.vendors.read,
    availability: 'pending',
    parentId: 'vendors.list',
  }),
  r({
    id: 'vendors.wallets',
    path: '/vendors/wallets',
    label: 'کیف فروشنده',
    sectionId: 'people',
    sectionLabel: 'کاربران و فروشندگان',
    template: 'list',
    permission: ADMIN_PERMISSIONS.vendors.read,
    availability: 'pending',
    parentId: 'vendors.list',
  }),

  // Finance
  r({
    id: 'finance.wallets',
    path: '/finance/wallets',
    label: 'کیف پول‌ها',
    sectionId: 'finance',
    sectionLabel: 'مالی',
    template: 'list',
    permission: ADMIN_PERMISSIONS.finance.read,
    availability: 'live',
    parentId: 'dashboard',
  }),
  r({
    id: 'finance.transactions',
    path: '/finance/transactions',
    label: 'تراکنش‌ها',
    sectionId: 'finance',
    sectionLabel: 'مالی',
    template: 'list',
    permission: ADMIN_PERMISSIONS.finance.read,
    availability: 'live',
    parentId: 'dashboard',
  }),
  r({
    id: 'finance.ledger',
    path: '/finance/ledger',
    label: 'دفتر کل',
    sectionId: 'finance',
    sectionLabel: 'مالی',
    template: 'list',
    permission: ADMIN_PERMISSIONS.ledger.read,
    availability: 'pending',
    parentId: 'dashboard',
  }),
  r({
    id: 'finance.accounting',
    path: '/finance/accounting',
    label: 'حسابداری',
    sectionId: 'finance',
    sectionLabel: 'مالی',
    template: 'list',
    permission: ADMIN_PERMISSIONS.ledger.read,
    availability: 'pending',
    parentId: 'dashboard',
  }),
  r({
    id: 'finance.reports',
    path: '/finance/reports',
    label: 'گزارش مالی',
    sectionId: 'finance',
    sectionLabel: 'مالی',
    template: 'list',
    permission: ADMIN_PERMISSIONS.finance.reports,
    availability: 'pending',
    parentId: 'dashboard',
  }),

  // Content
  r({
    id: 'cms.blog',
    path: '/cms/blog',
    label: 'وبلاگ',
    sectionId: 'content',
    sectionLabel: 'محتوا و رسانه',
    template: 'list',
    permission: ADMIN_PERMISSIONS.cms.read,
    availability: 'partial',
    parentId: 'dashboard',
  }),
  r({
    id: 'cms.homepage',
    path: '/cms/homepage',
    label: 'صفحه اصلی',
    sectionId: 'content',
    sectionLabel: 'محتوا و رسانه',
    template: 'settings',
    permission: ADMIN_PERMISSIONS.cms.write,
    availability: 'pending',
    parentId: 'dashboard',
  }),
  r({
    id: 'cms.banners',
    path: '/cms/banners',
    label: 'بنرها',
    sectionId: 'content',
    sectionLabel: 'محتوا و رسانه',
    template: 'list',
    permission: ADMIN_PERMISSIONS.cms.write,
    availability: 'pending',
    parentId: 'dashboard',
  }),
  r({
    id: 'cms.faq',
    path: '/cms/faq',
    label: 'سوالات متداول',
    sectionId: 'content',
    sectionLabel: 'محتوا و رسانه',
    template: 'list',
    permission: ADMIN_PERMISSIONS.cms.write,
    availability: 'pending',
    parentId: 'dashboard',
  }),
  r({
    id: 'cms.seo',
    path: '/cms/seo',
    label: 'SEO',
    sectionId: 'content',
    sectionLabel: 'محتوا و رسانه',
    template: 'settings',
    permission: ADMIN_PERMISSIONS.cms.write,
    availability: 'pending',
    parentId: 'dashboard',
  }),
  r({
    id: 'cms.pages',
    path: '/cms/pages',
    label: 'صفحات ثابت',
    sectionId: 'content',
    sectionLabel: 'محتوا و رسانه',
    template: 'list',
    permission: ADMIN_PERMISSIONS.cms.read,
    availability: 'pending',
    parentId: 'dashboard',
  }),
  r({
    id: 'media.library',
    path: '/media',
    label: 'کتابخانه رسانه',
    sectionId: 'content',
    sectionLabel: 'محتوا و رسانه',
    template: 'list',
    permission: ADMIN_PERMISSIONS.media.read,
    availability: 'pending',
    parentId: 'dashboard',
  }),
  r({
    id: 'media.upload',
    path: '/media/upload',
    label: 'آپلود',
    sectionId: 'content',
    sectionLabel: 'محتوا و رسانه',
    template: 'blank',
    permission: ADMIN_PERMISSIONS.media.write,
    availability: 'pending',
    parentId: 'media.library',
    nav: false,
  }),

  // Realtime
  r({
    id: 'realtime.feeds',
    path: '/realtime/feeds',
    label: 'فیدها',
    sectionId: 'realtime',
    sectionLabel: 'زمان‌واقعی',
    template: 'list',
    permission: ADMIN_PERMISSIONS.realtime.read,
    availability: 'pending',
    parentId: 'dashboard',
  }),
  r({
    id: 'realtime.subscriptions',
    path: '/realtime/subscriptions',
    label: 'اشتراک‌ها',
    sectionId: 'realtime',
    sectionLabel: 'زمان‌واقعی',
    template: 'list',
    permission: ADMIN_PERMISSIONS.realtime.read,
    availability: 'pending',
    parentId: 'realtime.feeds',
  }),
  r({
    id: 'realtime.config',
    path: '/realtime/config',
    label: 'پیکربندی',
    sectionId: 'realtime',
    sectionLabel: 'زمان‌واقعی',
    template: 'settings',
    permission: ADMIN_PERMISSIONS.realtime.configure,
    availability: 'pending',
    parentId: 'realtime.feeds',
  }),

  // Reports
  r({
    id: 'reports.sales',
    path: '/reports/sales',
    label: 'گزارش فروش',
    sectionId: 'reports',
    sectionLabel: 'گزارش‌ها',
    template: 'list',
    permission: ADMIN_PERMISSIONS.reports.view,
    availability: 'pending',
    parentId: 'dashboard',
  }),
  r({
    id: 'reports.inventory',
    path: '/reports/inventory',
    label: 'گزارش موجودی',
    sectionId: 'reports',
    sectionLabel: 'گزارش‌ها',
    template: 'list',
    permission: ADMIN_PERMISSIONS.reports.view,
    availability: 'pending',
    parentId: 'dashboard',
  }),
  r({
    id: 'reports.users',
    path: '/reports/users',
    label: 'گزارش کاربران',
    sectionId: 'reports',
    sectionLabel: 'گزارش‌ها',
    template: 'list',
    permission: ADMIN_PERMISSIONS.reports.view,
    availability: 'pending',
    parentId: 'dashboard',
  }),
  r({
    id: 'reports.vendors',
    path: '/reports/vendors',
    label: 'گزارش فروشندگان',
    sectionId: 'reports',
    sectionLabel: 'گزارش‌ها',
    template: 'list',
    permission: ADMIN_PERMISSIONS.reports.view,
    availability: 'pending',
    parentId: 'dashboard',
  }),
  r({
    id: 'reports.trading',
    path: '/reports/trading',
    label: 'گزارش معاملات',
    sectionId: 'reports',
    sectionLabel: 'گزارش‌ها',
    template: 'list',
    permission: ADMIN_PERMISSIONS.reports.view,
    availability: 'pending',
    parentId: 'dashboard',
  }),
  r({
    id: 'reports.financial',
    path: '/reports/financial',
    label: 'گزارش مالی',
    sectionId: 'reports',
    sectionLabel: 'گزارش‌ها',
    template: 'list',
    permission: ADMIN_PERMISSIONS.reports.view,
    availability: 'pending',
    parentId: 'dashboard',
  }),

  // Security
  r({
    id: 'security.audit',
    path: '/security/audit',
    label: 'لاگ ممیزی',
    sectionId: 'security',
    sectionLabel: 'امنیت',
    template: 'list',
    permission: ADMIN_PERMISSIONS.security.audit,
    availability: 'live',
    parentId: 'dashboard',
  }),
  r({
    id: 'security.sessions',
    path: '/security/sessions',
    label: 'نشست‌ها',
    sectionId: 'security',
    sectionLabel: 'امنیت',
    template: 'list',
    permission: ADMIN_PERMISSIONS.security.sessions,
    availability: 'pending',
    parentId: 'dashboard',
  }),
  r({
    id: 'security.loginHistory',
    path: '/security/login-history',
    label: 'تاریخچه ورود',
    sectionId: 'security',
    sectionLabel: 'امنیت',
    template: 'list',
    permission: ADMIN_PERMISSIONS.security.audit,
    availability: 'pending',
    parentId: 'dashboard',
  }),
  r({
    id: 'security.roles',
    path: '/security/roles',
    label: 'مدیریت نقش',
    sectionId: 'security',
    sectionLabel: 'امنیت',
    template: 'settings',
    permission: ADMIN_PERMISSIONS.security.rbac,
    availability: 'partial',
    parentId: 'dashboard',
  }),
  r({
    id: 'security.permissions',
    path: '/security/permissions',
    label: 'مدیریت دسترسی',
    sectionId: 'security',
    sectionLabel: 'امنیت',
    template: 'settings',
    permission: ADMIN_PERMISSIONS.security.rbac,
    availability: 'pending',
    parentId: 'dashboard',
  }),

  // Settings
  r({
    id: 'settings.home',
    path: '/settings',
    label: 'تنظیمات',
    sectionId: 'settings',
    sectionLabel: 'تنظیمات سیستم',
    template: 'settings',
    permission: ADMIN_PERMISSIONS.settings.read,
    availability: 'pending',
    parentId: 'dashboard',
  }),
  r({
    id: 'settings.general',
    path: '/settings/general',
    label: 'عمومی',
    sectionId: 'settings',
    sectionLabel: 'تنظیمات سیستم',
    template: 'settings',
    permission: ADMIN_PERMISSIONS.settings.read,
    availability: 'pending',
    parentId: 'settings.home',
  }),
  r({
    id: 'settings.commerce',
    path: '/settings/commerce',
    label: 'تجارت',
    sectionId: 'settings',
    sectionLabel: 'تنظیمات سیستم',
    template: 'settings',
    permission: ADMIN_PERMISSIONS.settings.write,
    availability: 'pending',
    parentId: 'settings.home',
  }),
  r({
    id: 'settings.gold',
    path: '/settings/gold',
    label: 'طلا',
    sectionId: 'settings',
    sectionLabel: 'تنظیمات سیستم',
    template: 'settings',
    permission: ADMIN_PERMISSIONS.settings.write,
    availability: 'pending',
    parentId: 'settings.home',
  }),
  r({
    id: 'settings.featureFlags',
    path: '/settings/feature-flags',
    label: 'Feature Flags',
    sectionId: 'settings',
    sectionLabel: 'تنظیمات سیستم',
    template: 'settings',
    permission: ADMIN_PERMISSIONS.settings.write,
    availability: 'pending',
    parentId: 'settings.home',
  }),
];

export const ADMIN_ROUTE_BY_ID = Object.fromEntries(
  ADMIN_ROUTES.map((route) => [route.id, route]),
) as Record<string, AdminRouteDefinition>;

/** Routes visible in sidebar (`nav !== false`). */
export const ADMIN_NAV_ROUTES = ADMIN_ROUTES.filter((route) => route.nav !== false);
