-- Product-level SEO metadata
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "seoTitle" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "seoKeywords" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "ogImageUrl" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "seoCanonicalPath" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "seoNoIndex" BOOLEAN NOT NULL DEFAULT false;
